Repository malcommac/SwiftLocation, pull requests merged in 2018-03, with the labels that each got.

#199 Update README.md
  README.md
Labels: documentation

#189 Fixed location from address geocoding
  Sources/GeocoderRequest.swift
Labels: bug, enhancement

#184 Use HTTPS for FreeGeoIP
  Sources/Shared.swift
Labels: enhancement

#178 Fixed minor typo in README
  README.md
Labels: documentation

#186 Add Google Places API language support
  README.md
  Sources/FindPlaceRequest.swift
  Sources/Locator.swift
  Sources/Shared.swift
Labels: bug, enhancement

#204 Fixed memory leaks into task closures
  README.md
  Sources/FindPlaceRequest.swift
  Sources/GeocoderRequest.swift
  Sources/IPLocationRequest.swift
  Sources/LocationRequest.swift
  Sources/Shared.swift
Labels: bug
