Repository malcommac/SwiftLocation, pull requests merged in 2020-11, with the labels that each got.

#302 Update README.md
  .github/.FUNDING.yml.icloud
  README.md
  banner.png
Labels: documentation

#309 kCLDistanceFilterNone value used as default for minDistance.
  Sources/SwiftLocation/CLLocationManager/LocationManagerImpProtocol.swift
  Sources/SwiftLocation/Extensions/CLLocationManager+Extension.swift
  Sources/SwiftLocation/Request/Requests/GPSLocation/GPSLocationOptions.swift
  Sources/SwiftLocation/Request/Requests/GPSLocation/GPSLocationRequest.swift
  Sources/SwiftLocation/SwiftLocation.swift
  SwiftLocationPlayground/SwiftLocationPlayground/View Controllers/Features/Location by GPS/GPSController.swift
  SwiftLocationPlayground/SwiftLocationPlayground/View Controllers/Requests List/RequestListController.swift
Labels: bug

#310 GPSLocationOptions's `timeout` variable is nullable.
  Sources/SwiftLocation/Request/Requests/GPSLocation/GPSLocationOptions.swift
Labels: bug

#305 Fix warnings for macCatalyst
  Sources/SwiftLocation/CLLocationManager/CLDeviceLocationManager/DeviceLocationManager.swift
  Sources/SwiftLocation/Extensions/CLLocationManager+Extension.swift
Labels: bug, enhancement
